AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  udemy-trello-clone

  Sample SAM Template for udemy-trello-clone

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  TSHttpApi:
    Type: AWS::Serverless:HttpApi
    Properties:
      CorsConfiguration:
      AllowOrigins:
        - "*"
      AllowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      AllowHeaders:
        - Access-Control-Allow-Origin
        - Authorization
        - Content-Type
      MaxAge: 600
      AllowCredentials: false

  GetCardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get-cards/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            ApiId: TSHttpApi
            Path: /cards
            Method: get

  CreateCardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/create-card/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            ApiId: TSHttpApi
            Path: /cards
            Method: post

  UpdateCardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/update-card/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            ApiId: TSHttpApi
            Path: /cards/{id}
            Method: put

  DeleteCardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/delete-card/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            ApiId: TSHttpApi
            Path: /cards/{id}
            Method: delete

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
